import "./globals.css";
import Topbar from "@/components/Topbar";

export const metadata = {
  title: "Video Editing AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto bg-[#F8F6F8]">
        <Topbar />
        {children}
      </body>
    </html>
  );
}
